# Generated by Django 5.2.8 on 2025-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('In progress', 'In progress'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
