# Generated by Django 5.2.8 on 2025-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('In progress', 'In progress'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
